// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateScene(arg1:string,arg2:string,arg3:string):Promise<main.SceneDTO>;

export function ListScenes():Promise<Array<main.SceneDTO>>;
