// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScene(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScene'](arg1, arg2, arg3);
}

export function ListScenes() {
  return window['go']['main']['App']['ListScenes']();
}
