// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Annotation struct {
	ID             string          `json:"id"`
	EntityID       string          `json:"entity_id"`
	AnnotationType string          `json:"annotation_type"`
	Content        string          `json:"content"`
	Metadata       json.RawMessage `json:"metadata"`
	AgentName      sql.NullString  `json:"agent_name"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Entity struct {
	ID         string          `json:"id"`
	VersionID  string          `json:"version_id"`
	EntityType string          `json:"entity_type"`
	Name       string          `json:"name"`
	Data       json.RawMessage `json:"data"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type GraphVersion struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	ParentVersionID sql.NullString `json:"parent_version_id"`
	Name            sql.NullString `json:"name"`
	Description     sql.NullString `json:"description"`
	IsWorkingSet    bool           `json:"is_working_set"`
	CreatedAt       time.Time      `json:"created_at"`
}

type Project struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Theme       sql.NullString `json:"theme"`
	Genre       sql.NullString `json:"genre"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Relationship struct {
	ID               string          `json:"id"`
	VersionID        string          `json:"version_id"`
	FromEntityID     string          `json:"from_entity_id"`
	ToEntityID       string          `json:"to_entity_id"`
	RelationshipType string          `json:"relationship_type"`
	Properties       json.RawMessage `json:"properties"`
	CreatedAt        time.Time       `json:"created_at"`
}

type Scene struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Summary   string    `json:"summary"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
